# Generated by Django 4.1.2 on 2022-10-22 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Webtoon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lang", models.CharField(max_length=100, verbose_name="언어")),
                ("platform", models.CharField(max_length=100, verbose_name="플랫폼")),
                ("webtoon", models.CharField(max_length=100, verbose_name="웹툰")),
            ],
            options={
                "verbose_name": "Webtoon",
                "verbose_name_plural": "Webtoon",
                "db_table": "Webtoon",
            },
        ),
    ]
